# Generated by Django 5.0.2 on 2024-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_task_list_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
